### ISSUE TITLE
usage of addon 

### ISSUE THREAD

**Issue by Andersonlimahw** [damiencaselli/ember-cli-google-fonts#5]
hi , i'm using this addon , and have a question, if a need another varitations of the same font a i need specific it too ?

another fonts availiable on google fonts are in this addon ?

Example : 

` googleFonts: [
      'Open+Sans:300',
      'Roboto:300, 400, 500, 600 , 700...'
    ],
`
or not ?

tnk's.

**Comment by damiencaselli** [comment]
Hi @Andersonlimahw,

Yes, fonts available from Google fonts can be included this way. This is actually the whole purpose of this addon.

For example, the following setting would add:

- Barrio (only exists in 400 flavour),
- Roboto as thin, regular and black,
- Sansita as regular, bold italic and black.

```
googleFonts: [
  'Barrio',
  'Roboto:100,400,900',
  'Sansita:400,700i,900'
]
```

Be sure to remove spaces when you declare fonts variations, there is no syntax check made by this addon.

**Comment by Andersonlimahw** [comment]
understand , tnks, @damiencaselli   .
